cc_test(
  name = "iterator_test",
  size = "small",
  srcs = ["iterator_test.cc"],
  deps = ["@com_google_googletest//:gtest_main", "iterator"],
)

cc_library(
  name = "iterator",
  srcs = ["iterator.cc"],
  hdrs = ["iterator.h"],
)